// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACf8qFBxWqOnv06YZiq27TnGkBpOuja_U',
    appId: '1:337956053801:web:ca120cda99d6ffcd12cd38',
    messagingSenderId: '337956053801',
    projectId: 'pharmacy-store-151c1',
    authDomain: 'pharmacy-store-151c1.firebaseapp.com',
    storageBucket: 'pharmacy-store-151c1.appspot.com',
    measurementId: 'G-Q4Y2DPWFRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUXyH9mqAqcTjyXFL2_RtV7wp54x9Uck',
    appId: '1:337956053801:android:09773e6274cea29112cd38',
    messagingSenderId: '337956053801',
    projectId: 'pharmacy-store-151c1',
    storageBucket: 'pharmacy-store-151c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsM_vb5onjNhWwVPejM7n5k4x5AeMUrkQ',
    appId: '1:337956053801:ios:fa94d0aed649abb812cd38',
    messagingSenderId: '337956053801',
    projectId: 'pharmacy-store-151c1',
    storageBucket: 'pharmacy-store-151c1.appspot.com',
    iosBundleId: 'com.example.pharmacyStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsM_vb5onjNhWwVPejM7n5k4x5AeMUrkQ',
    appId: '1:337956053801:ios:fa94d0aed649abb812cd38',
    messagingSenderId: '337956053801',
    projectId: 'pharmacy-store-151c1',
    storageBucket: 'pharmacy-store-151c1.appspot.com',
    iosBundleId: 'com.example.pharmacyStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACf8qFBxWqOnv06YZiq27TnGkBpOuja_U',
    appId: '1:337956053801:web:c664c502d844d1fe12cd38',
    messagingSenderId: '337956053801',
    projectId: 'pharmacy-store-151c1',
    authDomain: 'pharmacy-store-151c1.firebaseapp.com',
    storageBucket: 'pharmacy-store-151c1.appspot.com',
    measurementId: 'G-2ZHSBZGN9S',
  );
}
